env:
  browser: true
  es6: true
  node: true
  commonjs: true
  jest: true
extends: ['eslint:recommended', 'plugin:react/recommended']
parser: "babel-eslint"
parserOptions:
  sourceType: "module"
  ecmaVersion: 2018
rules:
  no-mixed-spaces-and-tabs:
    - 2
    - smart-tabs
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - never
